function is_valid_wpn(wpn)
    local section = wpn:section()
    local has_tristate_reload = ini_sys:r_string_ex(section,"tri_state_reload")

    -- Ignore weapons that are not jammed / at max ammo capacity
    local casted_wpn = wpn:cast_Weapon()
    if (not casted_wpn) or (not casted_wpn:IsMisfire() and casted_wpn:GetAmmoElapsed() == casted_wpn:GetAmmoMagSize()) then
        return false
    end

    if has_tristate_reload then
        if animation_common.has_animation(section, "anm_open_aim") then
            return true
        else
            return false
        end
    else
        if animation_common.has_animation(section, "anm_reload_aim") then
            return true
        else
            return false
        end
    end
end

function on_before_key_press(key, bind, dis, flags)
    if bind ~= key_bindings.kWPN_RELOAD then return end
    local wpn = db.actor:item_in_slot(db.actor:active_slot())
    if not wpn then return end
    if not is_valid_wpn(wpn) then return end
    if wpn:get_state() == 7 then return end

    wpn:switch_state(7)
    flags.ret_value = false

    --------------------------------------------------
    
    local ammo_total = 0
    local function check_ammo(temp, obj)
        if IsAmmo(obj) then
            local ammo_type = wpn:get_ammo_type()
            local weapon_section = wpn:section()
            local ammo_sections = parse_list(ini_sys, weapon_section, "ammo_class")
            if ammo_sections[ammo_type + 1] == obj:section() then
                ammo_total = ammo_total + obj:ammo_get_count()
            end
        end
    end
    db.actor:iterate_inventory(check_ammo, nil)

    if _G["agdd_voiced_actor"] and _G["agdd_voiced_actor"].actor_on_weapon_reload then
        _G["agdd_voiced_actor"].actor_on_weapon_reload(wpn, ammo_total)
    end

    --------------------------------------------------

end

function on_game_start()
    if magazines then return end
    RegisterScriptCallback("on_before_key_press", on_before_key_press)
end
